spring.application.name=JWT_springboot3
server.port=8005

# =======================================================
# CẤU HÌNH CƠ SỞ DỮ LIỆU (DATABASE CONFIGURATION)
# =======================================================
# 1. Cấu hình Microsoft SQL Server (Đang kích hoạt chạy trực tiếp trên máy)
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=jwt_springboot3;encrypt=false;trustServerCertificate=true;sslProtocol=TLSv1.2;characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. Cấu hình MySQL theo đúng slide bài giảng của ThS. Nguyễn Hữu Trung:
# (Nếu Thầy/Cô chấm bài bằng MySQL, chỉ cần đổi comment sang cấu hình dưới):
# spring.datasource.url=jdbc:mysql://localhost:3306/jwt_springboot3?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
# spring.datasource.username=root
# spring.datasource.password=1234567@a$
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =======================================================
# HIBERNATE / JPA (Tự động tạo bảng và ánh xạ Entity)
# =======================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# =======================================================
# JWT (NIMBUS JOSE+JWT)
# =======================================================
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in milliseconds
security.jwt.expiration-time=3600000
